更新 7.5.2 中文翻譯
rogeraabbccdd/GitKraken-zh-tw pull request #4
Opened 2021-03-06 10:46 UTC by SiongSng

2021-03-06 12:12 UTC, rogeraabbccdd requested changes

2021-03-06 12:12 UTC, rogeraabbccdd commented on strings.json
> +    "IssueTracker-GitHubSyncedBoardBlocksEditMessage": "這個看板和 GitHub 同步。請到 GitKraken 董事會 編輯這張卡片。",
Boards 應該是看板，而非董事會

2021-03-06 15:19 UTC, SiongSng commented on strings.json
> +    "IssueTracker-GitHubSyncedBoardBlocksEditMessage": "這個看板和 GitHub 同步。請到 GitKraken 董事會 編輯這張卡片。",
ok 感謝 因為有部分是機器翻譯的xd 我修正一下

2021-03-06 15:22 UTC, SiongSng commented on strings.json
> +    "IssueTracker-GitHubSyncedBoardBlocksEditMessage": "這個看板和 GitHub 同步。請到 GitKraken 董事會 編輯這張卡片。",
修改好囉

2021-03-07 05:31 UTC, rogeraabbccdd requested changes
還是有些地方需要修正

2021-03-07 05:31 UTC, rogeraabbccdd commented on strings.json
> +    "FuzzyFinder-ViewWorkingDirectoryChangesKeywords": "變更wip工作目錄",
這邊的 FuzzyFinder Keywords 是搜尋關鍵字，改成這樣會找不到

2021-03-07 05:31 UTC, rogeraabbccdd commented on strings.json
> +    "PullRequestPanel-GitHubDraftPullRequestTooltip": "合併請求草稿可用於 GitHub對組織免費 的公開儲存庫、舊儲存庫別付費方案及 GitHub 組織 和 GitHub企業雲 的公開及私人儲存庫。",
英文中文間要有空白

2021-03-07 05:31 UTC, rogeraabbccdd commented on strings.json
> +    "GitHubActionsTemplates-CCPPWithMake": "使用Mak的C/C++",
這裡應該是`Make`，而且英文中文間要有空格

2021-03-07 05:31 UTC, rogeraabbccdd commented on strings.json
> +    "GitHubActionTemplates-GreetFirstTimeContributors": "迎接首次投貢獻者",
好像多了一個 `投`？

2021-03-07 05:31 UTC, rogeraabbccdd commented on strings.json
> +    "GitHubActionForm-WorkflowName": "工作流程 名稱",
這裡的工作流程前面不需要空格

2021-03-07 05:50 UTC, SiongSng commented
修改好了w

2021-03-07 06:13 UTC, rogeraabbccdd requested changes

2021-03-07 06:13 UTC, rogeraabbccdd commented on strings.json
> +    "Profile-Unlock": "升級到 進階版 解鎖設定檔切換功能",
`進階版` 前後不需空格

2021-03-07 06:13 UTC, rogeraabbccdd commented on strings.json
> +    "PullRequestPanel-GitHubDraftPullRequestTooltip": "合併請求草稿可用於 GitHub 對組織免費 的公開儲存庫、舊儲存庫別付費方案及 GitHub 組織 和 GitHub企業雲 的公開及私人儲存庫。",
`免費`後不需空格

2021-03-07 06:13 UTC, rogeraabbccdd commented on strings.json
> +    "GitHubActionsTemplates-CCPPWithMake": "使用Make的C/C++",
`Make` 前後需要空格

2021-03-07 06:13 UTC, rogeraabbccdd commented on strings.json
> +    "GitHubActionForm-AddGitHubWorkflowButtonLabel": "建立 工作流程",
`工作流程` 不需空格

2021-03-07 06:13 UTC, rogeraabbccdd commented on strings.json
> +    "ContextMenu-GitHubActionEdit": "編輯 工作流程",
`工作流程` 不需空格

2021-03-07 06:13 UTC, rogeraabbccdd commented on strings.json
> +    "FuzzyFinder-StartPullRequestKeywords": "建立新的提取請求",
這裡沒改

2021-03-07 06:13 UTC, rogeraabbccdd commented on strings.json
> +    "FuzzyFinder-InitRepoKeywords": "初始化",
這裡沒改

2021-03-07 06:13 UTC, rogeraabbccdd commented on strings.json
> +    "FuzzyFinder-OpenInTerminalKeywords": "命令提示字元",
這裡沒改

2021-03-07 06:13 UTC, rogeraabbccdd commented on strings.json
> +    "FuzzyFinder-SettingsKeywords": "喜好設定",
這裡沒改

2021-03-07 06:13 UTC, rogeraabbccdd commented on strings.json
> +    "FuzzyFinder-ViewReleaseNotesKeywords": "補丁說明與變更日誌",
這裡沒改

2021-03-07 11:10 UTC, rogeraabbccdd commented
還是有很多空格的問題，也有些沒翻到  
算了我合併自己改

2021-03-07 11:12 UTC, rogeraabbccdd approved these changes
還是有很多空格的問題，也有些沒翻到  
算了我合併自己改

2021-03-07 11:12 UTC, merged

2021-03-07 11:14 UTC, SiongSng commented
OK，非常感謝，我下次會多多注意
可以麻煩你寫一個關於這個翻譯的準則嗎? (不然我不確定怎麼翻比較好)

2021-03-07 11:26 UTC, rogeraabbccdd commented
> 可以麻煩你寫一個關於這個翻譯的準則嗎? (不然我不確定怎麼翻比較好)

其實也沒什麼大問題，主要就是英文中文之間，還有中文數字之間要有一個空白做區隔  
可參考中文文案排版指北  
https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.md

2021-03-07 15:11 UTC, SiongSng commented
好的 感謝